Crre 469
OPEN-ENT-NG/crre pull request #40
Opened 2023-06-13 14:41 UTC by BastienBenard

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-06-16 16:16 UTC, JinDouang requested changes

2023-06-16 16:16 UTC, JinDouang commented on src/main/resources/public/ts/model/Basket.ts
> +            let url = `/crre/basketOrder/search?startDate=${startDate}&endDate=${endDate}&q=${text}`;
typage

2023-06-16 16:16 UTC, JinDouang commented on src/main/resources/public/ts/model/Basket.ts
> +            let url = `/crre/basketOrder/allMyOrders?idCampaign=${id_campaign}&idStructure=${structureId}`;
typage

2023-06-20 16:05 UTC, flmartineau approved these changes

2023-06-23 11:05 UTC, merged